/**
 * teamsSource — lista unica das equipas zerozero (fonte de verdade).
 *
 * reconciliacao: 9 URLs divergiam entre fetchZerozeroSquads.ts e
 * fetchZerozeroLogos.ts; ficam as URLs de candidates_2026_27.json
 * (todas com coverage complete, >=23 jogadores).
 * Os 3 scripts importam daqui — nao duplicar.
 */
export interface ZerozeroTeam { name: string; division: number; url: string; slug: string; }

export const TEAMS: ZerozeroTeam[] = [
  { name: "Sporting", division: 1, url: "/equipa/sporting", slug: "sporting" },
  { name: "Porto", division: 1, url: "/equipa/fc-porto", slug: "porto" },
  { name: "Benfica", division: 1, url: "/equipa/benfica", slug: "benfica" },
  { name: "Sp. Braga", division: 1, url: "/equipa/sc-braga", slug: "sp-braga" },
  { name: "Famalicão", division: 1, url: "/equipa/fc-famalicao/2175", slug: "famalicao" },
  { name: "Gil Vicente", division: 1, url: "/equipa/gil-vicente", slug: "gil-vicente" },
  { name: "Estoril", division: 1, url: "/equipa/estoril-praia/1734", slug: "estoril" },
  { name: "Moreirense", division: 1, url: "/equipa/moreirense/6", slug: "moreirense" },
  { name: "Marítimo", division: 2, url: "/equipa/maritimo", slug: "maritimo" },
  { name: "Ac.Viseu", division: 2, url: "/equipa/academico/2181", slug: "ac-viseu" },
  { name: "Torreense", division: 2, url: "/equipa/torreense/2178", slug: "torreense" },
  { name: "U. Leiria", division: 2, url: "/equipa/ud-leiria/17", slug: "u-leiria" },
  { name: "Vizela", division: 2, url: "/equipa/fc-vizela/2197", slug: "vizela" },
  { name: "Lus. Lourosa", division: 2, url: "/equipa/lusitania-de-lourosa/3599", slug: "lus-lourosa" },
  { name: "Feirense", division: 2, url: "/equipa/feirense/1728", slug: "feirense" },
  { name: "Chaves", division: 2, url: "/equipa/gd-chaves/20", slug: "chaves" },
  { name: "Amarante", division: 3, url: "/equipa/amarante-fc/4330", slug: "amarante" },
  { name: "Belenenses", division: 3, url: "/equipa/belenenses/3", slug: "belenenses" },
  { name: "Académica", division: 3, url: "/equipa/academica-oaf/19", slug: "academica" },
  { name: "Varzim", division: 3, url: "/equipa/varzim/36", slug: "varzim" },
  { name: "Mafra", division: 3, url: "/equipa/cd-mafra/3696", slug: "mafra" },
  { name: "U. Santarém", division: 3, url: "/equipa/u-santarem/3947", slug: "u-santarem" },
  { name: "Trofense", division: 3, url: "/equipa/trofense/3664", slug: "trofense" },
  { name: "Atlético", division: 3, url: "/equipa/atletico-cp/2170", slug: "atletico" },
  { name: "Bragança", division: 4, url: "/equipa/braganca/3565", slug: "braganca" },
  { name: "Vianense", division: 4, url: "/equipa/vianense/3672", slug: "vianense" },
  { name: "Rebordosa", division: 4, url: "/equipa/rebordosa-ac/3634", slug: "rebordosa" },
  { name: "Leça", division: 4, url: "/equipa/leca-fc/24", slug: "leca" },
  { name: "Vit. Sernache", division: 4, url: "/equipa/vitoria-sernache/5659", slug: "vit-sernache" },
  { name: "Louletano", division: 4, url: "/equipa/louletano/3596", slug: "louletano" },
  { name: "Juventude", division: 4, url: "/equipa/juventude-sc/3594", slug: "juventude" },
  { name: "Portel", division: 5, url: "/equipa/gd-portel/6803", slug: "portel" },
  { name: "U. Montemor", division: 5, url: "/equipa/grupo-uniao-sport/3712", slug: "u-montemor" },
  { name: "Monte do Trigo", division: 5, url: "/equipa/monte-trigo/3613", slug: "monte-do-trigo" },
  { name: "Vendas Novas", division: 5, url: "/equipa/estrela-fc/3581", slug: "vendas-novas" },
  { name: "At. Reguengos", division: 5, url: "/equipa/at-reguengos/6808?search=1", slug: "at-reguengos" },
  { name: "Sp. Viana", division: 5, url: "/equipa/sp-viana/10574", slug: "sp-viana" },
  { name: "Arcoense", division: 5, url: "/equipa/arcoense/6809", slug: "arcoense" },
  { name: "Redondense", division: 5, url: "/equipa/redondense/6807", slug: "redondense" },
  { name: "Arouca", division: 1, url: "/equipa/fc-arouca/3555?search=1", slug: "arouca" },
  { name: "Vitória SC", division: 1, url: "/equipa/vitoria-sc", slug: "vitoria-sc" },
  { name: "Alverca", division: 1, url: "/equipa/fc-alverca/1?search=1", slug: "alverca" },
  { name: "Rio Ave", division: 1, url: "/equipa/rio-ave/31?search=1", slug: "rio-ave" },
  { name: "Leixões", division: 2, url: "/equipa/leixoes/15", slug: "leixoes" },
  { name: "Felgueiras", division: 2, url: "/equipa/felgueiras-1932/3682", slug: "felgueiras" },
  { name: "Penafiel", division: 2, url: "/equipa/penafiel/14", slug: "penafiel" },
  { name: "Portimonense", division: 2, url: "/equipa/portimonense/13", slug: "portimonense" },
  { name: "Vit. Setúbal", division: 3, url: "/equipa/vitoria-fc/35?search=1", slug: "vit-setubal" },
  { name: "São João Ver", division: 3, url: "/equipa/s-joao-ver/3642?search=1", slug: "sao-joao-ver" },
  { name: "Fafe", division: 3, url: "/equipa/ad-fafe/3570", slug: "fafe" },
  { name: "Lusitano Évora", division: 3, url: "/equipa/lusitano-evora/4270", slug: "lusitano-evora" },
  { name: "Oliv. Hospital", division: 4, url: "/equipa/oliveira-hospital/3598", slug: "oliv-hospital" },
  { name: "Malveira", division: 4, url: "/equipa/at-malveira/3558?search=1", slug: "malveira" },
  { name: "Alcochetense", division: 4, url: "/equipa/alcochetense/3592", slug: "alcochetense" },
  { name: "O Elvas", division: 4, url: "/equipa/o-elvas/3604", slug: "o-elvas" },
  { name: "Sintrense", division: 4, url: "/equipa/sintrense/3590", slug: "sintrense" },
  { name: "Cabrela", division: 5, url: "/equipa/gd-cabrela/11054?search=1", slug: "cabrela" },
  { name: "Escouralense", division: 5, url: "/equipa/escouralense/6806?search=1", slug: "escouralense" },
  { name: "Aljustrelense", division: 5, url: "/equipa/aljustrelense/4327?search=1", slug: "aljustrelense" },
  { name: "Castrense", division: 5, url: "/equipa/fc-castrense/5657?search=1", slug: "castrense" },
];
